### ISSUE TITLE
Aliasing Behaviours?

### ISSUE THREAD

**Issue by toastal** [mikesol/purescript-hyrule#31]
> # Behaviors
>
> Or Behaviours if you're in 🇬🇧, 🇮🇪, 🇦🇺, 🇨🇦, 🇿🇦, 🇳🇿, 🇧🇼, 🇬🇲, 🇳🇦, 🇿🇲, ...

— Deku Docs, https://purescript-deku.netlify.app/functional-reactive-programming/behaviors

This is a bit weird TBH. Dialect v. nation one is currently located in aside, it looks like you spotted an issue by calling it out to begin with.

Could you imagine the burden of aliasing to worth it for accessibility for users? I’m of the “behaviors” camp myself, but I’ve watched coworkers struggle with dialectal issues with CSS and fingering a “colour” to get syntax errors. I mean look at this weirdness in JavaScript @ [`AnalyserNode`](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode) which I have spelled wrong a couple of times under the assumption that most Web APIs take on American English, or the annoyance of Nix with its `--optimise` flag I always spell wrong. It is not a good feeling when to you something is spelled correctly but the spellchecker or compiler tell you that you are wrong.

```purescript
module FRP.Behaviour where

import FRP.Behavior

type ABehaviour = ABehavior

type Behaviour = Behavior

-- etc.
```

As a precendence, the Erlang language seemlessly supports both behavior and behaviour as keywords (and oddly Purerl had decided only behaviour was valid).

Drawbacks: extra code to maintain, could be harder to use like Pursuit to find something (but for others it could be easier if they did not assume they should use a dialect they do not speak).

---

Useless anecdote: a while back I proposed semi-seriously a sigil like `%` to denote an alternate spelling to make this sort of thing better supported by docs which folks found silly

```
%myBehaviour
myBehavior ∷ ∀ a. a → Unit
myBehavior _ = unit
```

**Comment by toastal** [comment]
Ouch https://github.com/purescript-web/purescript-web-cssom-view/pull/6

**Comment by mikesol** [comment]
I'll leave this open but wait to make a change until someone requests it based on an issue they have using the lib.

**Comment by mikesol** [comment]
Renamed to `Poll`, which I believe is spelled that way in all dialects of English! 🇬🇧 🇺🇸 👽 (they speak English too... sometimes...)
