### ISSUE TITLE
rename master branch to main

### ISSUE THREAD

**Issue by srghma** [mikesol/purescript-hyrule#40]
purescript-contrib org does this

**Comment by mikesol** [comment]
Good call, let's do it! I'll invite you to the repo 👍

**Comment by srghma** [comment]
![2024-04-11-10am-09-48-screenshot](https://github.com/mikesol/purescript-hyrule/assets/7573215/be987f51-b02b-4ce0-91ea-a5f6aca23a29)

cannot rename 😂

https://github.com/mikesol/purescript-hyrule/branches

**Comment by mikesol** [comment]
Done!
